version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lead_management
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/lead_management
      - JWT_SECRET=your_jwt_secret_key_here
      - THIRD_PARTY_API_URL=
      - THIRD_PARTY_API_KEY=
      - ADMIN_PASSWORD=admin123
      - API_TOKEN=your_api_token_here
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_API_URL=http://backend:5000
      - API_TOKEN=your_api_token_here
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:

